import {supabase} from './supabase-client.js';
import {searchPattern,safeIdList,matchesSearch} from './clinic-search.js';
import {escapeText as esc} from './clinic-export.js';
export class PrescriptionBrowser{
 constructor({clinicId,patients,onView,onSign}){Object.assign(this,{clinicId,patients,onView,onSign});this.page=1;this.term='';this.status='';this.sequence=0;this.disposed=false;}
 mount(host){this.host=host;host.innerHTML=`<div class="record-search-tools"><label>Buscar receita<input type="search" autocomplete="off" placeholder="Paciente, telefone, título ou medicamento" data-rx-search></label><label>Situação<select data-rx-status><option value="">Todas</option><option value="signed">Assinadas</option><option value="pending_signature">Aguardando assinatura</option><option value="draft">Rascunhos</option></select></label></div><p class="search-feedback" role="status" data-rx-count></p><div data-rx-results></div>`;host.querySelector('[data-rx-search]').oninput=e=>{this.term=e.target.value;this.page=1;clearTimeout(this.timer);this.timer=setTimeout(()=>this.load(),250);};host.querySelector('[data-rx-status]').onchange=e=>{this.status=e.target.value;this.page=1;this.load();};this.load();}
 async medicationIds(pattern){let ids=[];for(let offset=0;offset<10000;offset+=500){const {data,error}=await supabase.from('prescription_items').select('prescription_id').eq('clinic_id',this.clinicId).ilike('medication_name',pattern).range(offset,offset+499);if(error)throw error;ids.push(...(data||[]).map(i=>i.prescription_id));if(safeIdList(ids).length>200)throw new Error('Há muitas receitas com esse medicamento. Use um nome mais específico.');if((data||[]).length<500)return safeIdList(ids);}throw new Error('Há muitos medicamentos correspondentes. Use um nome mais específico.');}
 async load(){const seq=++this.sequence;const feedback=this.host.querySelector('[data-rx-count]'),results=this.host.querySelector('[data-rx-results]');feedback.textContent='Buscando receitas em todo o histórico…';results.setAttribute('aria-busy','true');
 try{let query=supabase.from('prescriptions').select('*,prescription_items(id,medication_id,medication_name,instructions,position)',{count:'exact'}).eq('clinic_id',this.clinicId);if(this.status)query=query.eq('status',this.status);if(this.term.trim()){const pattern=searchPattern(this.term),patientIds=safeIdList(this.patients.filter(p=>matchesSearch(this.term,p.full_name,p.phone)).map(p=>p.id)),rxIds=await this.medicationIds(pattern);const filters=[`title.ilike.${pattern}`,`body.ilike.${pattern}`];if(patientIds.length)filters.push(`patient_id.in.(${patientIds.join(',')})`);if(rxIds.length)filters.push(`id.in.(${rxIds.join(',')})`);query=query.or(filters.join(','));}
 const {data,error,count}=await query.order('created_at',{ascending:false}).order('id').range((this.page-1)*12,this.page*12-1);if(error)throw error;if(this.disposed||seq!==this.sequence)return;this.records=data||[];this.total=count||0;feedback.textContent=`${this.total} receita(s) encontrada(s) em todo o histórico.`;results.innerHTML=this.records.length?this.records.map(r=>{const p=this.patients.find(p=>p.id===r.patient_id),meds=(r.prescription_items||[]).map(i=>i.medication_name).join(', ');return `<article class="simple-row record-row"><div><b>${esc(r.title||'Prescrição')}</b><small>${esc(p?.full_name||'Paciente')} · ${esc(new Date(r.created_at).toLocaleDateString('pt-BR'))}</small><small>${esc(meds)}</small></div><span class="status">${r.status==='signed'?'Assinada':'Aguardando assinatura'}</span><div class="consultation-actions"><button class="secondary" data-rx-view="${r.id}">Ver / imprimir</button>${r.status==='pending_signature'?`<button class="secondary" data-rx-sign="${r.id}">Assinar</button>`:''}</div></article>`;}).join(''):'<div class="empty-state"><h2>Nenhuma receita encontrada</h2><p>Ajuste a busca ou a situação selecionada.</p></div>';const pages=Math.max(1,Math.ceil(this.total/12));results.innerHTML+=`<nav class="pagination"><button class="secondary" data-rx-prev ${this.page===1?'disabled':''}>Anterior</button><small>Página ${this.page} de ${pages}</small><button class="secondary" data-rx-next ${this.page>=pages?'disabled':''}>Próxima</button></nav>`;results.querySelector('[data-rx-prev]').onclick=()=>{this.page--;this.load();};results.querySelector('[data-rx-next]').onclick=()=>{this.page++;this.load();};results.querySelectorAll('[data-rx-view]').forEach(b=>b.onclick=()=>this.onView(this.records.find(r=>r.id===b.dataset.rxView)));results.querySelectorAll('[data-rx-sign]').forEach(b=>b.onclick=()=>this.onSign(this.records.find(r=>r.id===b.dataset.rxSign)));
 }catch(error){if(!this.disposed&&seq===this.sequence){feedback.textContent=error.message||'Não foi possível consultar as receitas.';results.innerHTML='<button class="secondary" data-retry>Buscar novamente</button>';results.querySelector('[data-retry]').onclick=()=>this.load();}}finally{if(!this.disposed&&seq===this.sequence)results.removeAttribute('aria-busy');}}
 destroy(){this.disposed=true;this.sequence++;clearTimeout(this.timer);}
}
