import {readFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const source=(await readFile(new URL('../agenda-rules.js',import.meta.url),'utf8')).replace("import { supabase } from './supabase-client.js';",'const supabase=globalThis.agendaMock;');
let records=[];let failure=null;
globalThis.agendaMock={from(table){assert.equal(table,'appointments');let filters=[];const q={select(){return q},eq(k,v){filters.push(r=>r[k]===v);return q},neq(k,v){filters.push(r=>r[k]!==v);return q},lt(k,v){filters.push(r=>r[k]<v);return q},gt(k,v){filters.push(r=>r[k]>v);return q},limit(n){return Promise.resolve({data:records.filter(r=>filters.every(f=>f(r))).slice(0,n),error:failure})}};return q}};
const {validateAppointment,overlap}=await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'));
const start='2026-10-05T12:00:00.000Z',end='2026-10-05T13:00:00.000Z';
const appointment={id:'one',clinic_id:'clinic',starts_at:start,ends_at:end,status:'scheduled'};
assert.equal(overlap(start,end,end,'2026-10-05T14:00:00.000Z'),false);
assert.equal(overlap(start,end,'2026-10-05T12:30:00.000Z','2026-10-05T13:30:00.000Z'),true);
records=[appointment];
await assert.rejects(()=>validateAppointment('clinic',start,end),/já está reservado/);
await validateAppointment('clinic',end,'2026-10-05T14:00:00.000Z');
await validateAppointment('clinic',start,end,'one');
records=[{...appointment,status:'cancelled'}];await validateAppointment('clinic',start,end);
records=[{...appointment,clinic_id:'other'}];await validateAppointment('clinic',start,end);
await assert.rejects(()=>validateAppointment('clinic',end,start),/término/);
failure=new Error('Sem conexão');await assert.rejects(()=>validateAppointment('clinic',start,end),/Sem conexão/);
delete globalThis.agendaMock;
console.log('Agenda: sobreposição, limites adjacentes, edição, cancelamento, isolamento e falha de consulta verificados.');
