import assert from 'node:assert/strict';
import {financeState,financeTotals,addPayment} from '../finance-model.js';
import {normalizeSearch,matchesSearch,searchPattern,safeIdList} from '../clinic-search.js';
import {csvCell} from '../clinic-export.js';
const invoice={id:'doc',amount:1200,status:'issued',metadata:{source:'clinicorp'}};
assert.equal(financeState(invoice).state,'unreconciled');
assert.equal(financeTotals([invoice]).received,0,'An issued invoice is not a received payment');
assert.equal(financeTotals([invoice]).pending,0,'An unreconciled import is not automatically an account receivable');
const tracked={...invoice,metadata:{source:'clinicorp',finance:{tracking_started:true,due_date:'2026-01-01',payments:[]}}};
assert.equal(financeState(tracked,'2026-10-02').state,'overdue');
const metadata=addPayment(tracked,{amount:400,date:'2026-01-02',method:'pix',reference:'Comprovante de teste',confirmed:true},'actor');
assert.equal(metadata.source,'clinicorp');
const partial={...tracked,metadata};assert.equal(financeState(partial).state,'partial');assert.equal(financeState(partial).remaining,80000);
assert.equal(financeTotals([partial],'2026-10-02').overdue,80000);
assert.throws(()=>addPayment(partial,{amount:801,date:'2026-01-02',confirmed:true,reference:'test'},'actor'),/ultrapassa/);
assert.throws(()=>addPayment(partial,{amount:100,date:'2026-01-02',confirmed:false,reference:'test'},'actor'),/Confirme/);
assert.throws(()=>addPayment(partial,{amount:100,date:'2026-02-31',confirmed:true,reference:'test'},'actor'),/data/);
assert.throws(()=>addPayment(partial,{amount:100,date:'2026-01-02',confirmed:true,reference:''},'actor'),/referência/);
assert.throws(()=>addPayment(partial,{amount:-1,date:'2026-01-02',confirmed:true,reference:'test'},'actor'),/positivo/);
const paid={...partial,metadata:addPayment(partial,{amount:800,date:'2026-01-03',method:'card',reference:'test2',confirmed:true},'actor')};assert.equal(financeState(paid).state,'paid');assert.equal(financeState(paid).remaining,0);
const corrected={...paid,metadata:{...paid.metadata,finance:{...paid.metadata.finance,payments:paid.metadata.finance.payments.map((p,i)=>i===0?{...p,voided_at:'2026-01-04'}:p)}}};assert.equal(financeState(corrected).paid,80000);assert.equal(financeState(corrected).remaining,40000);
assert.equal(normalizeSearch(' João Ávila '),'joao avila');assert.equal(matchesSearch('avila','João Ávila','21975490550'),true);assert.equal(matchesSearch('97549','João Ávila','21975490550'),true);
assert.ok(!/[(),"']/g.test(searchPattern('"),clinic_id.neq.bad,(%')));
assert.deepEqual(safeIdList(['evil', '276f63b3-886a-0d8a-3bb9-b2e742da8ffa']),['276f63b3-886a-0d8a-3bb9-b2e742da8ffa']);
assert.equal(csvCell('=HYPERLINK("x")'),'"\'=HYPERLINK(""x"")"');assert.equal(csvCell('a;b'),'"a;b"');
console.log('Financeiro e busca: conciliação, recebimento parcial, saldo, correção, validações, preservação de importação e CSV verificados.');
