import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
const moduleURL=async name=>'data:text/javascript;base64,'+Buffer.from(await readFile(new URL('../'+name,import.meta.url),'utf8')).toString('base64');
const imports={};for(const name of ['clinic-search.js','clinic-export.js','finance-model.js'])imports[name]=await moduleURL(name);
let source=await readFile(new URL('../finance-panel.js',import.meta.url),'utf8');source=source.replace("import {supabase} from './supabase-client.js';",'const supabase=globalThis.recordQueryMock;');for(const [name,url] of Object.entries(imports))source=source.replace('./'+name,url);
const calls=[];let reply=null;
globalThis.recordQueryMock={from(table){let filters=[];const q={select(){return q},eq(k,v){filters.push(['eq',k,v]);return q},is(k,v){filters.push(['is',k,v]);return q},update(payload){calls.push({table,payload,filters});return q},or(term){calls.push({table,term});return q},order(){return q},range(offset,end){calls.push({table,offset,end});return Promise.resolve({data:Array.from({length:offset===0?500:3},(_,i)=>({id:String(offset+i),amount:10,status:'issued'})),error:null})},maybeSingle(){return Promise.resolve(reply)}};return q}};
const {FinancePanel}=await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'));
const panel=new FinancePanel({profile:{id:'actor',clinic_id:'clinic'},patients:[]});
const doc={id:'one',amount:10,status:'issued',metadata:{source:'imported'}};
reply={data:{...doc,metadata:{source:'imported',finance:{tracking_started:true}}},error:null};
await panel.saveMetadata(doc,reply.data.metadata);
assert.deepEqual(calls[0].filters,[['eq','clinic_id','clinic'],['eq','id','one'],['eq','metadata','{"source":"imported"}'],['eq','amount',10],['eq','status','issued']]);
reply={data:null,error:null};await assert.rejects(()=>panel.saveMetadata(doc,{}),/mudou/);
reply={data:null,error:new Error('Permissão negada')};await assert.rejects(()=>panel.saveMetadata(doc,{}),/Permissão/);
const nodes=new Map();panel.host={querySelector(selector){if(!nodes.has(selector))nodes.set(selector,{textContent:'',innerHTML:'',setAttribute(){},removeAttribute(){}});return nodes.get(selector);}};
let painted=false;panel.paint=()=>{painted=true;};panel.filters={from:'2026-10-01',to:'2026-10-02'};
await panel.load();assert.equal(panel.records.length,503);assert.equal(painted,true);assert.ok(calls.some(c=>c.offset===500));assert.ok(calls.some(c=>c.term?.includes('issued_at.is.null,created_at.gte.')));
assert.equal(panel.nextDay('2026-12-31'),'2027-01-01');
delete globalThis.recordQueryMock;
console.log('Consultas: totais além da primeira página, filtros de período, isolamento da clínica e gravação concorrente verificados.');
